#ifndef VERSION_H
#define VERSION_H

#define VER_DATE_INFO_STR        " - 12-Apr-2025"

#define VER_FILEVERSION          1,0,0,0
#define VER_FILEVERSION_STR      "1.0.0.0\0"

#define VER_PRODUCTVERSION       VER_FILEVERSION
#define VER_PRODUCTVERSION_STR   VER_FILEVERSION_STR

#define VER_COMPANYNAME_STR      ""
#define VER_FILEDESCRIPTION_STR  "PhaseNoiseAnalyzer"
#define VER_INTERNALNAME_STR     VER_FILEDESCRIPTION_STR
#define VER_LEGALCOPYRIGHT_STR   "Benjamin VERNOUX"
#define VER_LEGALTRADEMARKS1_STR ""
#define VER_LEGALTRADEMARKS2_STR VER_LEGALTRADEMARKS1_STR
#define VER_ORIGINALFILENAME_STR "PhaseNoiseAnalyzer.exe"
#define VER_PRODUCTNAME_STR      VER_FILEDESCRIPTION_STR

#endif // VERSION_H
